import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import MainLayout from "./MainLayout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Medicine E-commerce App",
  description: "Generated by Medicine E-commerce App",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-50`}
      >
        <MainLayout children={children}></MainLayout>
      </body>
    </html>
  );
}
